spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ugbe
    username: username
    password: password
  redis:
    host: localhost
    port: 6379
    password: password
